# SPDX-License-Identifier: MIT
"""`porthole docs` -- assemble the documentation site.

The site is *generated*, never hand-maintained. Its CLI reference comes from
the command registry, its tool catalogue from the tool headers, its profile-key
reference from `profiles/_template/device.env`, and its knowledge base from
`brain/`. Every page therefore has exactly one source of truth, and a page that
disagrees with the code is impossible rather than merely unlikely.

Output is MkDocs Material, which is what most modern Python projects publish
and what GitHub Pages hosts with one action. Building the site needs mkdocs
installed; *generating* it needs nothing, so `porthole docs build` works on a
bare host and CI does the rest.
"""
from __future__ import annotations

import os
import pathlib
import re
import shutil
import subprocess
import sys

from porthole_cli import Bail, EX_FAIL, EX_OK, EX_USAGE, discover, version

SITE_SRC = "site-src"

MKDOCS_YML = """\
# Generated by `porthole docs build`. Do not edit -- edit the sources instead.
site_name: porthole
site_description: A device bring-up toolkit for postmarketOS
site_url: https://{org}.github.io/{repo}/
repo_url: https://github.com/{org}/{repo}
repo_name: {org}/{repo}
edit_uri: ""

docs_dir: {src}
site_dir: site

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle: {{icon: material/brightness-auto, name: follow system}}
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle: {{icon: material/brightness-7, name: dark mode}}
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle: {{icon: material/brightness-4, name: light mode}}
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - toc.follow
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{org}/{repo}

nav:
{nav}
"""


def _yaml_key(text: str) -> str:
    """Quote a nav title for YAML.

    Note titles routinely contain a colon -- "Playbook: first boot" -- and an
    unquoted colon-space is a YAML mapping, so the file fails to parse with an
    error pointing at a line that looks perfectly fine.
    """
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _nav(entries, indent=2) -> str:
    """Render a nav tree. entries is a list of (title, path-or-list)."""
    out = []
    pad = " " * indent
    for title, target in entries:
        if isinstance(target, list):
            out.append(f"{pad}- {_yaml_key(title)}:")
            out.append(_nav(target, indent + 4))
        else:
            out.append(f"{pad}- {_yaml_key(title)}: {target}")
    return "\n".join(out)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


# ------------------------------------------------------------- generators --

def page_cli(root: pathlib.Path) -> str:
    """The CLI reference, from the live command registry."""
    specs = discover(root)
    out = ["# Command reference", "",
           "Generated from the command registry. Every verb is one "
           "`lib/porthole_cmd_<name>.py` file exporting a `SPEC` dict.", "",
           "| verb | what it does |", "|---|---|"]
    for spec in specs:
        out.append(f"| [`{spec['verb']}`](#{_slug(spec['verb'])}) | {spec['help']} |")
    out.append("")

    for spec in specs:
        out += [f"## {spec['verb']}", ""]
        desc = spec.get("description") or spec["help"]
        out += [desc, ""]
        if spec.get("args"):
            out += ["| argument | description |", "|---|---|"]
            for flags, kwargs in spec["args"]:
                names = ", ".join(f"`{f}`" for f in flags)
                help_text = (kwargs.get("help") or "").replace("|", "\\|")
                choices = kwargs.get("choices")
                if choices:
                    help_text += f" *(one of: {', '.join(map(str, choices))})*"
                out.append(f"| {names} | {help_text} |")
            out.append("")
        if spec.get("examples"):
            out += ["```console"]
            for ex in spec["examples"]:
                out.append(f"$ {ex}")
            out += ["```", ""]
    return "\n".join(out)


def page_tools(root: pathlib.Path) -> str:
    """The tool catalogue, from each tool's own header."""
    sys.path.insert(0, str(root / "lib"))
    from porthole_cmd_tools import collect

    profiles = [p.name for p in sorted((root / "profiles").iterdir())
                if p.is_dir() and not p.name.startswith("_")]
    tools = collect(root)
    for profile in profiles:
        tools += [t for t in collect(root, profile) if "profiles" in t.path.parts]

    out = ["# Tool catalogue", "",
           f"{len(tools)} tools, generated from their own headers.", "",
           "`needs` is the device state a tool requires: `-` host-only, "
           "`BOOTED`, `FASTBOOT`, `on-device` (it runs *on* the device), or "
           "`any` (it probes and handles several).", "",
           "!!! tip \"Searching this from a shell\"",
           "    `porthole tools --grep <what>` and `porthole tools --needs "
           "BOOTED` do the same filtering, and `porthole tools <name>` prints "
           "one tool's contract.", ""]

    by_scope: dict[str, list] = {}
    for tool in tools:
        by_scope.setdefault(tool.scope or "generic", []).append(tool)

    for scope in sorted(by_scope, key=lambda s: (s != "generic", s)):
        out += [f"## `{scope}`", "",
                "| tool | needs | what it does |", "|---|---|---|"]
        for tool in sorted(by_scope[scope], key=lambda t: t.name):
            needs = (tool.needs or "-").split("(")[0].strip() or "-"
            summary = (tool.summary or "").replace("|", "\\|")[:110]
            out.append(f"| `{tool.name}` | {needs} | {summary} |")
        out.append("")
    return "\n".join(out)


def page_profile_keys(root: pathlib.Path) -> str:
    """The profile-key reference, from the documented template."""
    template = root / "profiles" / "_template" / "device.env"
    out = ["# Device profile keys", "",
           "Every key a device profile can set, from "
           "`profiles/_template/device.env`.", "",
           "Keys marked **TRAP** encode a lesson from a previous port. Getting "
           "one wrong does not produce an error -- it produces a confident "
           "wrong answer.", ""]
    if not template.is_file():
        return "\n".join(out + ["*(template missing)*"])

    section = None
    pending: list[str] = []
    for raw in template.read_text().splitlines():
        line = raw.rstrip()
        header = re.match(r"^#\s*-{4,}\s*(.+?)\s*-{2,}$", line)
        if header:
            section = header.group(1).strip()
            out += ["", f"## {section.title()}", ""]
            pending = []
            continue
        if line.startswith("#"):
            body = line.lstrip("#").strip()
            if body and not set(body) <= set("-= "):
                pending.append(body)
            continue
        m = re.match(r'^([A-Z_]+)=(.*)$', line)
        if not m:
            continue
        key, default = m.group(1), m.group(2)
        inline = ""
        if "#" in default:
            default, _, inline = default.partition("#")
        default = default.strip().strip('"')
        notes = " ".join(pending + ([inline.strip()] if inline.strip() else []))
        pending = []
        trap = "**TRAP** " if "(TRAP)" in notes else ""
        notes = notes.replace("(TRAP)", "").strip()
        default_txt = f"`{default}`" if default else "*(unset)*"
        out.append(f"### `{key}`")
        out.append("")
        out.append(f"default: {default_txt}")
        if notes:
            out += ["", f"{trap}{notes}"]
        out.append("")
    return "\n".join(out)


def _brain_map(brain: pathlib.Path) -> dict[str, pathlib.Path]:
    """note id -> its path, so a [[wikilink]] can be resolved across sections.

    A law is linked from a workflow note and a trap from a playbook; resolving
    the link relative to the *linking* file points at a sibling that does not
    exist. The id is globally unique by convention, so map it once.
    """
    out: dict[str, pathlib.Path] = {}
    for path in sorted(brain.rglob("*.md")):
        if path.name == "INDEX.md":
            continue
        out[path.stem] = path.relative_to(brain)
        # Prefer the frontmatter id where it differs from the filename.
        try:
            head = path.read_text(errors="replace")[:400]
        except OSError:
            continue
        m = re.search(r"^id:\s*(\S+)", head, re.M)
        if m:
            out[m.group(1)] = path.relative_to(brain)
    return out


def _resolve_links(body: str, here: pathlib.Path,
                   index: dict[str, pathlib.Path]) -> str:
    """Turn [[note-id]] into a working relative markdown link."""
    def replace(match):
        target = match.group(1).split("/")[-1]
        dest = index.get(target)
        if dest is None:
            # A link to a note nobody has written yet is a marker, not an
            # error -- brain/README.md says to link liberally. Render it as
            # plain text rather than a broken link.
            return f"`{target}`"
        rel = os.path.relpath(dest, here.parent)
        return f"[{target}]({pathlib.PurePosixPath(rel)})"
    return re.sub(r"\[\[([a-z0-9/-]+)\]\]", replace, body)


def copy_brain(root: pathlib.Path, dest: pathlib.Path) -> dict[str, list]:
    """Copy brain notes, turning frontmatter into a rendered header."""
    sections: dict[str, list] = {}
    brain = root / "brain"
    index = _brain_map(brain)
    for path in sorted(brain.rglob("*.md")):
        rel = path.relative_to(brain)
        if rel.name == "INDEX.md":
            continue
        section = rel.parts[0]
        text = path.read_text(errors="replace")
        meta, body = {}, text
        m = re.match(r"\A---\s*\n(.*?)\n---\s*\n(.*)\Z", text, re.S)
        if m:
            for line in m.group(1).splitlines():
                if ":" in line:
                    k, _, v = line.partition(":")
                    meta[k.strip()] = v.strip().strip('"')
            body = m.group(2)

        header = []
        if meta.get("title"):
            header += [f"# {meta['title']}", ""]
        chips = []
        for field in ("scope", "severity", "confidence", "subsystem"):
            if meta.get(field):
                chips.append(f"**{field}**: `{meta[field]}`")
        if chips:
            header += [" · ".join(chips), ""]
        if meta.get("evidence"):
            header += [f'!!! quote "Evidence"', f"    {meta['evidence']}", ""]

        body = _resolve_links(body, rel, index)

        target = dest / "brain" / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("\n".join(header) + body)
        sections.setdefault(section, []).append(
            (meta.get("title", rel.stem), f"brain/{rel.as_posix()}"))
    return sections


def cmd_build(args, ctx) -> int:
    root = ctx.root
    src = root / SITE_SRC
    if src.exists():
        shutil.rmtree(src)
    src.mkdir(parents=True)

    # -- hand-written pages, copied verbatim --
    (src / "index.md").write_text(
        _readme_as_index((root / "README.md").read_text()))
    for name, title in [("SANDBOX.md", "Running pmbootstrap safely"),
                        ("CONFIG.md", "Configuration"),
                        ("ARCHITECTURE.md", "Architecture"),
                        ("PERFORMANCE.md", "Performance"),
                        ("CONTRIBUTING.md", "Contributing")]:
        source = root / "docs" / name
        if source.is_file():
            (src / name.lower()).write_text(source.read_text())
    agents = root / "AGENTS.md"
    if agents.is_file():
        (src / "agents.md").write_text(agents.read_text())

    # -- generated reference --
    (src / "cli.md").write_text(page_cli(root))
    (src / "tools.md").write_text(page_tools(root))
    (src / "profile-keys.md").write_text(page_profile_keys(root))

    # -- the brain --
    sections = copy_brain(root, src)

    nav = [
        ("Home", "index.md"),
        ("Guides", [
            ("Running pmbootstrap safely", "sandbox.md"),
            ("Configuration", "config.md"),
            ("Performance", "performance.md"),
            ("Architecture", "architecture.md"),
            ("Contributing", "contributing.md"),
        ]),
        ("Reference", [
            ("Commands", "cli.md"),
            ("Tools", "tools.md"),
            ("Profile keys", "profile-keys.md"),
        ]),
        ("For agents", "agents.md"),
    ]
    brain_nav = []
    if (src / "brain" / "README.md").is_file():
        brain_nav.append(("How to read this", "brain/README.md"))
    for section in ("laws", "traps", "playbooks", "workflow", "devices",
                    "memory"):
        if section in sections:
            brain_nav.append((section.title(),
                              sorted(sections[section], key=lambda x: x[1])))
    if brain_nav:
        nav.append(("Knowledge base", brain_nav))

    (root / "mkdocs.yml").write_text(MKDOCS_YML.format(
        org=args.org or "Pixel-pmOS", repo=args.repo or "porthole",
        src=SITE_SRC, nav=_nav(nav)))

    pages = sum(1 for _ in src.rglob("*.md"))

    def render():
        o = ctx.out
        o(f"{o.paint(o.sym('✓', 'ok'), 'green')} generated {pages} pages "
          f"into {SITE_SRC}/")
        o(f"  mkdocs.yml written for {args.org or 'Pixel-pmOS'}/"
          f"{args.repo or 'porthole'}")
        o.blank()
        o(o.paint("  Nothing here is hand-maintained: the CLI reference comes "
                  "from the\n  command registry, the tool catalogue from the "
                  "tool headers, the\n  profile keys from the template, and the "
                  "knowledge base from brain/.", "grey"))
        o.blank()
        if shutil.which("mkdocs"):
            o.hint("porthole docs serve    preview at http://127.0.0.1:8000")
        else:
            o.hint("pipx install mkdocs-material    then `porthole docs serve`")
        o.hint("git push — CI builds and publishes it to GitHub Pages")

    return ctx.emit({"pages": pages, "src": str(src)}, render)


# The README links by repository path; the site is flat. Rewriting these is
# what lets one README serve both audiences instead of maintaining two.
README_LINK_MAP = {
    "docs/SANDBOX.md": "sandbox.md",
    "docs/CONFIG.md": "config.md",
    "docs/PERFORMANCE.md": "performance.md",
    "docs/ARCHITECTURE.md": "architecture.md",
    "docs/CONTRIBUTING.md": "contributing.md",
    "docs/TOOLS.md": "tools.md",
    "AGENTS.md": "agents.md",
    "skills/porthole-bringup/": "https://github.com/Pixel-pmOS/porthole/tree/main/skills/porthole-bringup",
    "LICENSE": "https://github.com/Pixel-pmOS/porthole/blob/main/LICENSE",
}


def _readme_as_index(text: str) -> str:
    """The README works as a landing page, minus its table of contents.

    The site has real navigation, so an in-page TOC of anchors that no longer
    all exist is worse than none.
    """
    for old, new in README_LINK_MAP.items():
        text = text.replace(f"]({old})", f"]({new})")
    out, skipping = [], False
    for line in text.splitlines():
        if line.strip() == "## Table of contents":
            skipping = True
            continue
        if skipping:
            if line.startswith("---") or (line.startswith("## ")):
                skipping = False
            else:
                continue
        out.append(line)
    return "\n".join(out)


def cmd_serve(args, ctx) -> int:
    if not shutil.which("mkdocs"):
        raise Bail("mkdocs is not installed", EX_FAIL,
                   "pipx install mkdocs-material   (a docs-only dependency; "
                   "the toolkit itself needs nothing)")
    if not (ctx.root / SITE_SRC).is_dir():
        cmd_build(args, ctx)
    return subprocess.run(["mkdocs", "serve"], cwd=ctx.root).returncode


ACTIONS = {"build": cmd_build, "serve": cmd_serve}


def dispatch(args, ctx) -> int:
    action = args.action or "build"
    fn = ACTIONS.get(action)
    if not fn:
        raise Bail(f"unknown action {action!r}", EX_USAGE,
                   f"actions: {', '.join(ACTIONS)}")
    return fn(args, ctx)


SPEC = {
    "verb": "docs",
    "order": 92,
    "help": "generate the documentation site",
    "description": (
        "The site is generated, never hand-maintained: the CLI reference from\n"
        "the command registry, the tool catalogue from the tool headers, the\n"
        "profile keys from the template, the knowledge base from brain/.\n\n"
        "Every page has one source of truth, so a page that disagrees with the\n"
        "code is impossible rather than merely unlikely."),
    "args": [
        (["action"], {"nargs": "?", "metavar": "ACTION", "choices": list(ACTIONS),
                      "help": "build | serve"}),
        (["--org"], {"help": "GitHub org/user for links (default Pixel-pmOS)"}),
        (["--repo"], {"help": "repository name (default porthole)"}),
        (["--json"], {"action": "store_true", "help": "machine-readable"}),
    ],
    "run": dispatch,
    "examples": ["porthole docs build", "porthole docs serve"],
}
