#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""`porthole new-device` -- scaffold a profile for a device nobody has ported.

Scaffolds and seeds. It deliberately does NOT try to generate a working
deviceinfo, defconfig or DTS: every device differs, and a confidently wrong
auto-generated deviceinfo costs more than an empty one -- you debug the device
instead of the file.

What it can honestly answer, it answers: `fastboot getvar all` knows the slot
count and the current slot, and an existing pmaports device package knows the
screen size and the boot image offsets. Everything else is marked TODO with a
pointer to the playbook that resolves it.
"""
from __future__ import annotations

import difflib
import pathlib
import re
import shutil
import subprocess
import sys

from porthole_cli import Bail, EX_FAIL, EX_OK, EX_USAGE


CHECKLIST = """# {codename} — bring-up checklist

Generated by `porthole new-device {codename}`. Tick as you go; every item links
to the playbook that explains it.

Run `porthole doctor` first. It will tell you what is missing on the host.

## 0. Before the device

- [ ] Find an existing device tree for this SoC — a sibling device's DTS is
      worth more than a blank page
- [ ] Find the closest pmaports device package to copy from (same SoC beats
      same vendor)
- [ ] Read `brain/playbooks/00-device-protocol.md` once
- [ ] Read `brain/laws/` — ten notes, and they are what stops you wasting weeks

## 1. First boot — `brain/playbooks/10-first-boot.md`

- [ ] Boot image offsets sourced, **not guessed**
- [ ] **Check whether this device can RAM-boot at all** —
      `porthole brain search --scope device:{codename}` before you rely on it.
      `fastboot boot` leaves the installed system alone and is the usual safety
      net, but it is NOT universal: on some devices the bootloader ignores the
      ramdisk, and then every test image is a *flash*. Establish which you have
      before the first write, not after.
- [ ] If it cannot RAM-boot: set `PORTHOLE_SLOT_FORBIDDEN` and keep a known-good
      image on the other slot BEFORE flashing anything
- [ ] A channel out that works before the display: earlycon, debug shell, or
      the USB gadget
- [ ] Classify boots with `tools/boot-probe.sh`, not by eye

## 2. Storage, USB, ssh — `brain/playbooks/20-storage-usb-ssh.md`

- [ ] Storage controller probes, partitions enumerate
- [ ] USB gadget up; host sees the interface
- [ ] ssh answers
- [ ] Passwordless sudo installed on the device (see `porthole init` output) —
      without it every tool silently does nothing
- [ ] `porthole doctor` is clean

## 3. Fill in the profile

Each of these is a fact you will otherwise re-derive at 3am. Set them in
`profiles/{codename}/device.env` as soon as you know them.

- [ ] `PORTHOLE_BOOT_RETRIES` — the every-Nth-boot countdown
- [ ] `PORTHOLE_SLOT_FORBIDDEN` — any slot with no known-good image
- [ ] `PORTHOLE_USB_LIES_AS_FASTBOOT` — does lsusb mislabel the running gadget?
- [ ] `PORTHOLE_REBOOT_MODE_VIA_SYSCALL` — is /usr/sbin/reboot busybox?
- [ ] `PORTHOLE_WATCHDOG_MAX_S` — the hardware ceiling
- [ ] `PORTHOLE_REBOOT_BUDGET_S` — **measured**: cold boot to first ssh

## 4. Subsystems, in order

- [ ] Display — `brain/playbooks/30-display.md`
- [ ] Suspend — `brain/playbooks/40-suspend.md` (this dominates daily-driver)
- [ ] Radios — `brain/playbooks/50-wifi-bt-modem.md`
- [ ] Daily driver — `brain/playbooks/60-daily-driver.md`

## 5. Upstream — `brain/playbooks/90-upstreaming.md`

- [ ] Commits written as if being sent today
- [ ] Anything that benefits other SoCs split into its own commit
"""


def getvar_all(fastboot: str) -> dict[str, str]:
    """Parse `fastboot getvar all`. Returns {} if no device is in the bootloader.

    fastboot writes getvar output to stderr, which is worth knowing before you
    spend time wondering why stdout is empty.
    """
    try:
        proc = subprocess.run([fastboot, "getvar", "all"],
                              capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return {}
    out = {}
    for line in (proc.stderr + proc.stdout).splitlines():
        m = re.match(r"^\(bootloader\)\s+([^:]+):\s*(.*)$", line.strip())
        if m:
            out[m.group(1).strip()] = m.group(2).strip()
    return out


def seed_from_fastboot(vals: dict[str, str]) -> dict[str, str]:
    seeded = {}
    slots = vals.get("slot-count") or vals.get("has-slot:boot")
    if slots and slots not in ("0", "no"):
        seeded["PORTHOLE_HAS_AB_SLOTS"] = "1"
        current = vals.get("current-slot", "").strip(" _")
        if current:
            seeded["PORTHOLE_ACTIVE_SLOT"] = current
    elif slots is not None:
        seeded["PORTHOLE_HAS_AB_SLOTS"] = "0"
    for key, var in (("product", "PORTHOLE_CODENAME"),
                     ("hw-revision", "PORTHOLE_HW_REVISION")):
        if vals.get(key):
            seeded[var] = vals[key]
    return seeded


DEVICEINFO_MAP = {
    "deviceinfo_name": "PORTHOLE_DEVICE_NAME",
    "deviceinfo_manufacturer": "PORTHOLE_VENDOR",
    "deviceinfo_codename": "PORTHOLE_CODENAME",
    "deviceinfo_year": "PORTHOLE_YEAR",
    "deviceinfo_arch": "PORTHOLE_ARCH",
    "deviceinfo_screen_width": "PORTHOLE_SCREEN_WIDTH",
    "deviceinfo_screen_height": "PORTHOLE_SCREEN_HEIGHT",
    "deviceinfo_dtb": "PORTHOLE_DTB",
    "deviceinfo_flash_pagesize": "PORTHOLE_BOOTIMG_PAGESIZE",
    "deviceinfo_flash_offset_base": "PORTHOLE_BOOTIMG_BASE",
    "deviceinfo_flash_offset_kernel": "PORTHOLE_BOOTIMG_KERNEL_OFFSET",
    "deviceinfo_flash_offset_ramdisk": "PORTHOLE_BOOTIMG_RAMDISK_OFFSET",
    "deviceinfo_flash_offset_tags": "PORTHOLE_BOOTIMG_TAGS_OFFSET",
    "deviceinfo_header_version": "PORTHOLE_BOOTIMG_HEADER_VERSION",
}


def seed_from_deviceinfo(path: pathlib.Path) -> dict[str, str]:
    """Read an existing pmaports deviceinfo. These values are already trusted by
    a working device package, which is a far better source than a guess."""
    seeded = {}
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    for line in text.splitlines():
        line = line.strip()
        if "=" not in line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        target = DEVICEINFO_MAP.get(key.strip())
        if target:
            seeded[target] = value.strip().strip('"').strip("'")
    return seeded


# A comment that is only an example value -- `# "Google Pixel 2 XL"` -- is
# guidance for a blank. Once the key is filled it is noise, and worse, it is
# another device's name sitting next to yours.
EXAMPLE_COMMENT = re.compile(r'^#\s*"[^"]*"\s*$')


def apply_seeds(template: str, seeds: dict[str, str]) -> tuple[str, list[str]]:
    """Fill seeded keys in the template, leave the rest as documented blanks."""
    filled = []
    lines = template.splitlines(True)
    for i, line in enumerate(lines):
        # Match a filled default too, not only a blank. The template ships
        # PORTHOLE_HAS_AB_SLOTS="0" and PORTHOLE_ARCH="aarch64" as sensible
        # defaults -- but a seed comes from an authoritative source (fastboot
        # getvar, a sibling's deviceinfo, the caller), and a default that
        # silently outranks it is worse than no default at all. `getvar`
        # reporting two slots was being dropped on the floor here, which is
        # exactly the value you must not get wrong before a first flash.
        m = re.match(r'^([A-Z_]+)=("[^"]*")?\s*(#.*)?$', line.rstrip("\n"))
        if not m:
            continue
        key = m.group(1)
        if key in seeds:
            comment = m.group(3) or ""
            # Keep a real explanation (the (TRAP) notes), drop a stale example.
            comment = "" if EXAMPLE_COMMENT.match(comment) else comment
            lines[i] = f'{key}="{seeds[key]}"' + (f"  {comment}" if comment else "") + "\n"
            filled.append(key)
    return "".join(lines), filled


TEMPLATE_HEADER = """# porthole device profile — TEMPLATE
#
# Copy this with `porthole new-device <codename>`, then fill it in as you learn.
# Every key is listed even when you cannot answer it yet: an empty key you can
# see is a question you know to ask, and a key that is simply absent is not."""


def retitle(content: str, codename: str, seeds: dict) -> str:
    """The scaffolded file is this device's profile, not a template any more."""
    name = seeds.get("PORTHOLE_DEVICE_NAME", "")
    title = f"{name} ({codename})" if name else codename
    return content.replace(TEMPLATE_HEADER, f"""# porthole device profile — {title}
#
# Scaffolded by `porthole new-device {codename}`. Every blank below is a
# question you now know to ask; fill them in as you learn the answers.
# `profiles/{codename}/checklist.md` is the order to learn them in.""", 1)


def cmd_new_device(args, ctx) -> int:
    root = pathlib.Path(ctx.root)
    codename = args.codename
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", codename):
        raise Bail(f"codename must be lowercase alphanumeric with dashes: "
                   f"{codename!r}", EX_USAGE,
                   "pmOS convention is <vendor>-<codename>, e.g. google-taimen")

    dest = root / "profiles" / codename
    if dest.exists() and not args.force:
        raise Bail(f"profiles/{codename} already exists", EX_FAIL,
                   "re-run with --force to overwrite it")

    template = (root / "profiles" / "_template" / "device.env").read_text()

    seeds = {"PORTHOLE_CODENAME": codename}
    notes: list[str] = []
    unknown_soc = ""

    if args.from_fastboot:
        import porthole
        cfg = porthole.load_config(root=root)
        vals = getvar_all(cfg.get("FASTBOOT") or "fastboot")
        if vals:
            got = seed_from_fastboot(vals)
            seeds.update(got)
            notes.append(f"seeded {len(got)} key(s) from `fastboot getvar all`")
        else:
            notes.append("no device in the bootloader — nothing seeded from "
                         "fastboot")

    # 1. An existing pmaports package for THIS device is the best source there
    #    is: those values are already trusted by something that boots.
    import porthole_pmaports as pmap
    pmaports = pmap.find_pmaports(getattr(ctx, "cfg", None) if ctx else None)
    sibling = None
    if pmaports:
        own = list(pmaports.rglob(f"device-{codename}/deviceinfo"))
        if own:
            got = seed_from_deviceinfo(own[0])
            seeds.update(got)
            notes.append(f"seeded {len(got)} key(s) from its own pmaports "
                         f"package")

        # 2. Otherwise -- the common case for a device nobody has ported --
        #    the closest sibling on the same SoC. Its boot image offsets are
        #    known to boot, which is worth more than any amount of guessing.
        if not own or args.soc:
            devices = pmap.load_devices(pmaports)
            known = sorted({d.soc for d in devices if d.soc})
            soc = args.soc
            explicit_miss = False
            if soc and soc not in known:
                # An unknown SoC must NOT be fatal. `--soc google-gs201` for
                # silicon nobody has ported is precisely what this verb exists
                # for -- and note that a SUCCESSOR generation is one character
                # from its predecessor by design, so "looks like a typo" cannot
                # distinguish the two. Treating a near-miss as fatal rejected
                # google-gs201 for resembling google-gs101, which is the exact
                # port this was built to start.
                #
                # What actually needs protecting against is seeding from the
                # WRONG silicon, and the fix for that is to not seed at all:
                # an explicitly named SoC that does not exist skips the
                # vendor-inference fallback below, so no sibling is ever
                # chosen on the strength of a name that turned out to be
                # nothing.
                explicit_miss = True
                unknown_soc = soc
                near = difflib.get_close_matches(soc, known, n=3, cutoff=0.6)
                note = (f"SoC {soc!r} is not used by any pmaports device — "
                        f"nothing seeded")
                if near:
                    note += (f"; closest existing: {', '.join(near)} "
                             f"(a typo, or the previous generation?)")
                else:
                    note += " (expected for new silicon; if it is a BOARD "\
                            "name, the SoC belongs here)"
                notes.append(note)
                ctx.out.warn(note)
                soc = ""
            if not soc and not explicit_miss:
                # Infer from a same-vendor device, then give up rather than
                # guess: seeding from the wrong silicon is worse than blanks.
                # Skipped entirely when the user NAMED a SoC that turned out
                # not to exist -- falling back after that would seed from
                # silicon they never asked for.
                vendor = codename.split("-")[0]
                same_vendor = [d for d in devices
                               if d.codename.startswith(vendor + "-") and d.soc]
                soc = same_vendor[0].soc if len(
                    {d.soc for d in same_vendor}) == 1 else ""
            if soc:
                sibs = [d for d in pmap.siblings(devices, soc)
                        if d.codename != codename]
                if sibs:
                    sibling = sibs[0]
                    got = seed_from_deviceinfo(sibling.path / "deviceinfo")
                    # Never let a sibling's identity leak into your profile.
                    for key in ("PORTHOLE_DEVICE_NAME", "PORTHOLE_VENDOR",
                                "PORTHOLE_CODENAME", "PORTHOLE_YEAR",
                                "PORTHOLE_SCREEN_WIDTH", "PORTHOLE_SCREEN_HEIGHT",
                                "PORTHOLE_DTB"):
                        got.pop(key, None)
                    for key, value in got.items():
                        seeds.setdefault(key, value)
                    seeds.setdefault("PORTHOLE_SOC", soc.split("-", 1)[-1])
                    notes.append(f"seeded {len(got)} key(s) from "
                                 f"{sibling.codename} ({sibling.category}), the "
                                 f"closest device on {soc}")

    content, filled = apply_seeds(template, seeds)
    content = retitle(content, codename, seeds)
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "device.env").write_text(content)
    (dest / "checklist.md").write_text(CHECKLIST.format(codename=codename))
    (dest / "tools").mkdir(exist_ok=True)
    (dest / "tools" / ".gitkeep").write_text("")
    # No notes.md. It was a third place for device notes to live, competing
    # with brain/ (for what generalises) and $PORTHOLE_WORKDIR/docs/ (for what
    # does not). Three homes for one kind of file is how taimen/docs/ became 65
    # flat entries.

    blanks = len(re.findall(r'^[A-Z_]+=""\s*(?:#.*)?$', content, re.M))
    payload = {
        "codename": codename,
        "profile": str(dest),
        "seeded_from": ([sibling.codename] if sibling else []),
        "sibling_soc": (sibling.soc if sibling else ""),
        "unknown_soc": unknown_soc,
        "keys_filled": len(filled),
        "keys_blank": blanks,
        "filled": sorted(filled),
        "notes": notes,
    }

    def render():
        o = ctx.out
        o(f"created profiles/{codename}/")
        for note in notes:
            o(f"  {note}")
        # ALWAYS say whether sibling seeding happened. The original defect was
        # not that `--soc cloudripper` was accepted -- it was that it was
        # accepted SILENTLY, leaving an unseeded profile indistinguishable from
        # a seeded one.
        if not sibling:
            o(f"  {o.paint('no sibling seeding', 'yellow')} — every value below "
              f"is yours to establish")
        o(f"  {len(filled)} key(s) filled, {blanks} still blank")
        if sibling:
            o.blank()
            o("  Inherited values come from a device that BOOTS, which beats")
            o("  guessing -- but same SoC does not guarantee same board.")
            o("  Verify the boot image offsets against your own device's")
            o("  downstream mkbootimg args or an unpacked stock boot.img.")
            o(f"    porthole soc inherit {sibling.codename}")
        o.blank()
        o("next:")
        o(f"  1. read   profiles/{codename}/checklist.md")
        o(f"  2. fill   profiles/{codename}/device.env  (every blank is a "
          f"question you now know to ask)")
        o(f"  3. run    porthole use {codename}")
        o(f"  4. read   porthole brain search --severity law")

    return ctx.emit(payload, render)


SPEC = {
    "verb": "new-device",
    "order": 70,
    "help": "scaffold a profile for a device nobody has ported yet",
    "description": (
        "Copies the documented template, seeds what can honestly be known from\n"
        "`fastboot getvar all` and any existing pmaports deviceinfo, and writes\n"
        "a checklist wired to the playbooks.\n\n"
        "It does NOT invent a deviceinfo, defconfig or DTS. A confidently wrong\n"
        "one costs more than a blank: you end up debugging the device instead\n"
        "of the file."),
    # The positional IS the device, so no -d/--device selector is injected:
    # it would be a second way to name a device that means the opposite one.
    "device_flag": False,
    "args": [
        (["codename"], {"help": "lowercase, dashes; e.g. oneplus-enchilada"}),
        (["--from-fastboot"], {"action": "store_true",
                               "help": "seed from a device in the bootloader"}),
        (["--soc"], {"metavar": "SOC",
                     "help": "seed from the closest sibling on this SoC, "
                             "vendor-prefixed, e.g. qcom-sdm845"}),
        (["--force"], {"action": "store_true", "help": "overwrite an existing profile"}),
        (["--json"], {"action": "store_true", "help": "machine-readable"}),
    ],
    "run": cmd_new_device,
    "examples": [
        "porthole new-device oneplus-enchilada",
        "porthole new-device fairphone-fp4 --from-fastboot",
        "porthole new-device google-cheetah --soc google-gs201   # new silicon",
    ],
}
