#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# scope: generic
# needs: - (host only, no device)
# env: -
# exits: 0 ok
"""Generate docs/TOOLS.md from the tool headers. Run via `make tools-doc`.

Generated rather than hand-written so it cannot drift: the header in the tool is
the single source of truth, and a catalogue that disagrees with the tools is
worse than no catalogue.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "lib"))

from porthole_cmd_tools import collect  # noqa: E402

GROUPS = [
    ("Boot, flash and recovery", ("boot", "flash", "reboot", "fastboot",
                                  "recover", "dtbo", "bootimg", "to-fastboot")),
    ("Device state and supervision", ("device", "supervise", "deadman", "soak",
                                      "stallwatch", "lifeline", "hang", "cycle")),
    ("Power, suspend and thermal", ("suspend", "thermal", "sysstate", "osm",
                                    "cpufreq", "usb-wake")),
    ("Display and GPU", ("fps", "dpu", "display", "gesture", "firstpaint",
                         "ringdump", "perf")),
    ("Camera", ("phy", "cam", "vfe", "chromatix", "awb", "easel", "sensorstream",
                "tgstream")),
    ("Audio", ("audio", "mic", "acoustic", "alsa", "tone", "wav", "tas", "dmic",
               "gap")),
    ("Touch and input", ("touch", "evtest", "mtstate", "ftm4", "key")),
    ("Sensors", ("iio", "prox", "compass", "mount", "sns", "sensor")),
    ("Radios", ("wifi", "lte", "qrtr", "modem")),
    ("Build and packaging", ("build", "pkg", "modcrc", "push-module", "reconcile")),
    ("Low level", ("i2c", "spi", "regdump", "pins", "dtb", "fdt", "pil", "kmsg")),
]


def group_of(name: str) -> str:
    for title, keys in GROUPS:
        if any(k in name for k in keys):
            return title
    return "Other"


def main() -> int:
    tools = collect(ROOT, "google-taimen")
    buckets: dict[str, list] = {}
    for tool in tools:
        buckets.setdefault(group_of(tool.name), []).append(tool)

    print("# Tool catalogue")
    print()
    print("Generated by `make tools-doc` from each tool's own header. Do not edit.")
    print()
    print("`porthole tools` is the searchable version of this; "
          "`porthole tools --json` is the machine-readable one.")
    print()
    print("**needs** is the device state a tool requires: `-` host-only, "
          "`BOOTED`, `FASTBOOT`, `on-device` (it runs *on* the device), or "
          "`any` (it probes and handles several).")
    print()
    print(f"{len(tools)} tools.")
    print()

    for title, _ in GROUPS + [("Other", ())]:
        chosen = sorted(buckets.get(title, []), key=lambda t: t.name)
        if not chosen:
            continue
        print(f"## {title}")
        print()
        print("| tool | needs | scope | what it does |")
        print("|---|---|---|---|")
        for tool in chosen:
            needs = tool.needs.split("(")[0].strip() or "-"
            summary = tool.summary.replace("|", "\\|")[:110]
            mark = " *(profile)*" if tool.kind == "profile" else ""
            print(f"| `{tool.name}`{mark} | {needs} | `{tool.scope}` | {summary} |")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
